# Docker Compose file for SQLite
# GitHub: https://github.com/vintagedon/docker-compose-cookbook
# Description: This Docker Compose file sets up a container with SQLite and optional web-based management tool.

version: '3.8'
services:
  sqlite:
    image: keinos/sqlite3:latest
    container_name: ${SQLITE_CONTAINER_NAME}
    volumes:
      - ${SQLITE_DATA_DIR}:/data
    environment:
      - SQLITE_DATABASE=${SQLITE_DATABASE}
      - SQLITE_JOURNAL_MODE=${SQLITE_JOURNAL_MODE:-WAL}
      - SQLITE_SYNCHRONOUS=${SQLITE_SYNCHRONOUS:-NORMAL}
      - SQLITE_TEMP_STORE=${SQLITE_TEMP_STORE:-MEMORY}
      - SQLITE_MMAP_SIZE=${SQLITE_MMAP_SIZE:-0}
      - SQLITE_CACHE_SIZE=${SQLITE_CACHE_SIZE:--2000}
    command: tail -f /dev/null  # Keeps the container running

  sqlite-web:
    image: coleifer/sqlite-web:latest
    container_name: ${SQLITE_WEB_CONTAINER_NAME}
    depends_on:
      - sqlite
    volumes:
      - ${SQLITE_DATA_DIR}:/data
    environment:
      - SQLITE_DATABASE=/data/${SQLITE_DATABASE}
    ports:
      - "${SQLITE_WEB_PORT}:8080"

networks:
  default:
    name: sqlite_network
