version: "3.8"

services:
  gogs:
    image: gogs/gogs:${GOGS_VERSION:-latest}
    container_name: ${CONTAINER_NAME:-gogs}
    ports:
      - "${GOGS_HTTP_PORT:-3000}:3000"
      - "${GOGS_SSH_PORT:-22}:22"
    volumes:
      - gogs_data:/data
      - gogs_config:/data/gogs/conf
    environment:
      - GOGS_CUSTOM=/data/gogs
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - RUN_MODE=${RUN_MODE:-prod}
      - DOMAIN=${DOMAIN:-localhost}
      - ROOT_URL=${ROOT_URL:-http://localhost:3000/}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  gogs_data:
  gogs_config:

networks:
  default:
    name: gogs_network
