# Docker Compose file for MongoDB
# GitHub: https://github.com/vintagedon/docker-compose-cookbook
# Description: This Docker Compose file sets up a MongoDB instance with customizable configuration.

version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      - ${MONGO_CONFIG_DIR}:/data/configdb
    command: mongod --auth --bind_ip_all
      --setParameter maxTransactionLockRequestTimeoutMillis=${MONGO_MAX_TRANSACTION_LOCK_REQUEST_TIMEOUT:-5000}
      --setParameter maxTransactionLockRequestTimeoutMillis=${MONGO_MAX_TRANSACTION_LOCK_REQUEST_TIMEOUT:-5000}
      --setParameter cursorTimeoutMillis=${MONGO_CURSOR_TIMEOUT:-600000}
      --setParameter maxTimeMS=${MONGO_MAX_TIME_MS:-600000}
      --wiredTigerCacheSizeGB ${MONGO_CACHE_SIZE:-0.5}

  mongo-express:
    image: mongo-express:latest
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb

networks:
  default:
    name: mongodb_network
