version: "3.8"

services:
  gogs:
    image: gogs/gogs:${GOGS_VERSION:-latest}
    container_name: ${GOGS_CONTAINER_NAME:-gogs}
    ports:
      - "${GOGS_HTTP_PORT:-3000}:3000"
      - "${GOGS_SSH_PORT:-22}:22"
    volumes:
      - gogs_data:/data
      - ./scripts/init.sql:/data/init.sql
    environment:
      - GOGS_CUSTOM=/data/gogs
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0}
    container_name: ${MYSQL_CONTAINER_NAME:-gogs-mysql}
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-gogs}
      - MYSQL_USER=${MYSQL_USER:-gogs}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

volumes:
  gogs_data:
  mysql_data:

networks:
  default:
    name: gogs_network
