# Docker Compose file for Prometheus
# GitHub: https://github.com/vintagedon/docker-compose-cookbook/tree/main/monitoring-logging/Prometheus
# Description: This Docker Compose file sets up a Prometheus instance with customizable configuration.

version: '3.8'
services:
  prometheus:
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ${PROMETHEUS_CONFIG_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_DATA_DIR}:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME}'
      - '--web.enable-lifecycle'
    environment:
      - TZ=UTC
    restart: unless-stopped

networks:
  default:
    name: prometheus_network
