# Docker Compose file for Grafana
# GitHub: https://github.com/vintagedon/docker-compose-cookbook/tree/main/monitoring-logging/Grafana
# Description: This Docker Compose file sets up a Grafana instance with customizable configuration.

version: '3.8'
services:
  grafana:
    container_name: ${GRAFANA_CONTAINER_NAME}
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ${GRAFANA_CONFIG_DIR}:/etc/grafana
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
    restart: unless-stopped

networks:
  default:
    name: grafana_network
