# Name: compose.yaml
#
# Description:
# Docker Compose file for a standlone installation of InfluxDB
# https://www.influxdata.com/
# 
#
# Project: https://github.com/vintagedon/infrastructure-scripting/blob/main/docker-compose/
# License: Apache-2.0

version: '2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "${INFLUXDB_PORT_PUBLIC}:8086"
    volumes:
      - ${INFLUXDB_DIRECTORY_ETC}/appdata/influxdb2/config:/etc/influxdb2
      - ${INFLUXDB_DIRECTORY_VARLIB}/appdata/influxdb2/db:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=${INFLUX_DB}
      - INFLUXDB_ADMIN_USER=${INFLUX_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_ADMIN_PASSWORD}
