# Docker Compose file for Gitea with PostgreSQL
# GitHub: https://github.com/vintagedon/docker-compose-cookbook/development-ci-cd/gitea-postgresql
# Description: This Docker Compose file sets up a Gitea instance with PostgreSQL database and customizable configuration.

version: "3.8"
services:
  gitea:
    container_name: ${CONTAINER_NAME:-gitea}
    image: gitea/gitea:latest
    ports:
      - "${HTTP_PORT:-3000}:3000"
      - "${SSH_PORT:-22}:22"
    volumes:
      - gitea-data:/data
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - GITEA__server__ROOT_URL=${GITEA__server__ROOT_URL:-http://localhost:3000/}
      - GITEA__server__SSH_DOMAIN=${GITEA__server__SSH_DOMAIN:-localhost}
      - GITEA__server__SSH_PORT=${SSH_PORT:-22}
      - GITEA__server__DOMAIN=${GITEA__server__DOMAIN:-localhost}
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/sbin/gitea", "status"]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 5s

  postgres:
    container_name: gitea-postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gitea-data:
  gitea-config:
  postgres-data:

networks:
  default:
    name: gitea_postgres_network
