version: "3.8"

services:
  rundeck:
    image: rundeck/rundeck:${RUNDECK_VERSION:-latest}
    container_name: ${CONTAINER_NAME:-rundeck}
    environment:
      - RUNDECK_DATABASE_DRIVER=org.mariadb.jdbc.Driver
      - RUNDECK_DATABASE_USERNAME=${RUNDECK_DB_USER:-rundeck}
      - RUNDECK_DATABASE_PASSWORD=${RUNDECK_DB_PASSWORD:-rundeck}
      - RUNDECK_DATABASE_URL=jdbc:mariadb://db/rundeck?autoReconnect=true&useSSL=false
      - RUNDECK_GRAILS_URL=${RUNDECK_URL:-http://localhost:4440}
      - RUNDECK_SERVER_ADDRESS=0.0.0.0
      - RUNDECK_SERVER_FORWARDED=true
    volumes:
      - rundeck_data:/home/rundeck/server/data
      - rundeck_logs:/home/rundeck/server/logs
      - rundeck_plugins:/home/rundeck/libext
      - ./scripts/init.sh:/home/rundeck/init.sh
    ports:
      - "${RUNDECK_PORT:-4440}:4440"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4440"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  db:
    image: mariadb:${MARIADB_VERSION:-10.5}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=${RUNDECK_DB_USER:-rundeck}
      - MYSQL_PASSWORD=${RUNDECK_DB_PASSWORD:-rundeck}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  rundeck_data:
  rundeck_logs:
  rundeck_plugins:
  mariadb_data:

networks:
  default:
    name: rundeck_network
