version: "3.8"

services:
  redis:
    image: redis:${REDIS_VERSION:-latest}
    container_name: ${CONTAINER_NAME:-redis}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./scripts/init.redis:/data/init.redis
    command: redis-server --appendonly ${REDIS_APPENDONLY:-yes} --requirepass ${REDIS_PASSWORD:-changeme}
    environment:
      - REDIS_MAXMEMORY=${REDIS_MAXMEMORY:-256mb}
      - REDIS_MAXMEMORY_POLICY=${REDIS_MAXMEMORY_POLICY:-allkeys-lru}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:

networks:
  default:
    name: redis_network
