# Docker Compose file for GitLab CE
# GitHub: https://github.com/vintagedon/docker-compose-cookbook/development-ci-cd/gitlabce
# Description: This Docker Compose file sets up a GitLab CE instance with customizable configuration.

version: '3.8'
services:
  gitlab:
    container_name: ${CONTAINER_NAME}
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${SSH_PORT}
        gitlab_rails['incoming_email_enabled'] = ${INCOMING_EMAIL_ENABLED}
        gitlab_rails['incoming_email_address'] = '${GITLAB_INCOMING_EMAIL_ADDRESS}'
        # SMTP configuration
        gitlab_rails['smtp_enable'] = ${SMTP_ENABLED}
        gitlab_rails['smtp_address'] = "${SMTP_HOST}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        # GitLab Pages configuration
        gitlab_pages['enable'] = ${GITLAB_PAGES_ENABLED}
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
      - '${SSH_PORT}:22'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab_network

networks:
  gitlab_network:
    name: gitlab_network
