version: "3.8"

services:
  gitea:
    image: gitea/gitea:${GITEA_VERSION:-latest}
    container_name: ${GITEA_CONTAINER_NAME:-gitea}
    environment:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${POSTGRES_DB:-gitea}
      - GITEA__database__USER=${POSTGRES_USER:-gitea}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD:-gitea_password}
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_HTTP_PORT:-3000}:3000"
      - "${GITEA_SSH_PORT:-22}:22"
    depends_on:
      - postgres

  postgres:
    image: postgres:${POSTGRES_VERSION:-13-alpine}
    container_name: ${POSTGRES_CONTAINER_NAME:-gitea-postgres}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gitea}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gitea_password}
      - POSTGRES_DB=${POSTGRES_DB:-gitea}
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  gitea:
    driver: bridge

volumes:
  gitea_data:
  postgres_data:
