# Ansible Role: linux-updates-apt
# Description: Updates Linux servers using apt and reboots if necessary
#
# Workflow
# 1. Update the APT cache
# 2. Check for updates
# 3. Upgrade all packages to latest version (dist)
# 4. Check for reboot required; if so, do the needful.
# 5. Wait for server to reboot; notify.
---
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Check for Updates
  command: /usr/lib/update-notifier/apt-check --package-names
  register: pkg_list

- name: Upgrade all packages to latest version (dist)
  apt:
    upgrade: dist
  when: pkg_list.stderr != ""

- name: Check for reboot required via reboot_flag
  stat: path=/var/run/reboot-required get_md5=no
  register: reboot_flag

- name: If server needs rebooting, do the needful
  reboot:
    reboot_timeout: 300
  when: reboot_flag.stat.exists == true

- debug:
    msg: "Server is back up and running"
