version: "3.8"

services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:${MONGO_VERSION:-4}
    container_name: ${MONGO_CONTAINER_NAME:-mongodb}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION:-7.10.2}
    container_name: ${ES_CONTAINER_NAME:-elasticsearch}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms${ES_JAVA_OPTS_XMS:-512m} -Xmx${ES_JAVA_OPTS_XMX:-512m}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: ${ES_MEM_LIMIT:-1g}

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:${GRAYLOG_VERSION:-4.2}
    container_name: ${GRAYLOG_CONTAINER_NAME:-graylog}
    volumes:
      - graylog_data:/usr/share/graylog/data
      - ./scripts/init.sh:/usr/local/bin/init.sh
    restart: unless-stopped
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET:-somepasswordpepper}
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2:-8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI:-http://127.0.0.1:9000/}
      - GRAYLOG_ELASTICSEARCH_HOSTS=${GRAYLOG_ELASTICSEARCH_HOSTS:-http://elasticsearch:9200}
      - GRAYLOG_MONGODB_URI=${GRAYLOG_MONGODB_URI:-mongodb://admin:password@mongodb:27017/graylog?authSource=admin}
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - ${GRAYLOG_HTTP_PORT:-9000}:9000
      # Syslog TCP
      - ${GRAYLOG_SYSLOG_TCP_PORT:-1514}:1514
      # Syslog UDP
      - ${GRAYLOG_SYSLOG_UDP_PORT:-1514}:1514/udp
      # GELF TCP
      - ${GRAYLOG_GELF_TCP_PORT:-12201}:12201
      # GELF UDP
      - ${GRAYLOG_GELF_UDP_PORT:-12201}:12201/udp

volumes:
  mongodb_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local

networks:
  default:
    name: graylog_network
