# Name: create-ubuntu2204-proxmox-template.sh
# Description:
#   Docker compose file for SWAG (Secure Application Gateway)
#   Pulls wildcard certificates via LetsCrypt for the listed domain
#   https://github.com/linuxserver/docker-swag
# 
#  NOTE: Values are set for my environment, see the Usage section 
#  for additional information. Also referece the SWAG docker flags at
#  https://github.com/linuxserver/docker-swag?tab=readme-ov-file#usage
#
# Project: https://github.com/vintagedon/infrastructure-scripting
# License: Apache-2.0
#
# USAGE:
# Customize / change the following values
# 
# TZ -- your timezone
# URL -- the domain/subdomain to install SWAG to
# 


---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=swag.beardinthe.cloud
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
      - EMAIL= alerts@beardinthe.cloud
    volumes:
      - /portdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
