# Docker Compose file for AdGuard Home
# GitHub: https://github.com/vintagedon/docker-compose-cookbook
# Description: This Docker Compose file sets up an AdGuard Home instance with customizable configuration.

version: '3.8'
services:
  adguardhome:
    container_name: ${ADGUARD_CONTAINER_NAME}
    image: adguard/adguardhome:latest
    ports:
      - "${ADGUARD_HTTP_PORT}:3000"
      - "${ADGUARD_DNS_PORT}:53/tcp"
      - "${ADGUARD_DNS_PORT}:53/udp"
    volumes:
      - ${ADGUARD_CONFIG_DIR}:/opt/adguardhome/conf
      - ${ADGUARD_WORK_DIR}:/opt/adguardhome/work
    restart: unless-stopped
    networks:
      - adguard_network

networks:
  adguard_network:
    name: adguard_network
