version: "3.8"

services:
  softethervpn:
    image: siomiz/softethervpn:${SOFTETHER_VERSION:-latest}
    container_name: ${CONTAINER_NAME:-softethervpn}
    ports:
      - "${VPN_PORT:-5555}:5555/tcp"
      - "${VPN_PORT:-5555}:5555/udp"
      - "${OPENVPN_PORT:-1194}:1194/tcp"
      - "${OPENVPN_PORT:-1194}:1194/udp"
      - "${L2TP_PORT:-500}:500/udp"
      - "${L2TP_PORT:-4500}:4500/udp"
      - "${SSTP_PORT:-443}:443/tcp"
    volumes:
      - softethervpn_data:/opt/vpn_server
      - ./scripts/init.sh:/opt/vpn_server/init.sh
    environment:
      - SPW=${SERVER_PASSWORD:-ChangeThisPassword}
      - HPW=${HUB_PASSWORD:-ChangeThisHubPassword}
      - USERS=${VPN_USERS:-user1:password1,user2:password2}
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  softethervpn_data:

networks:
  default:
    name: softethervpn_network
