version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:${JENKINS_VERSION:-lts-jdk11}
    container_name: ${CONTAINER_NAME:-jenkins}
    user: root
    ports:
      - "${JENKINS_HTTP_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_sqlite:/var/jenkins_sqlite
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/init.groovy:/usr/share/jenkins/ref/init.groovy.d/init.groovy
    environment:
      - JENKINS_OPTS=${JENKINS_OPTS:---httpPort=8080}
      - JENKINS_SLAVE_AGENT_PORT=${JENKINS_AGENT_PORT:-50000}
      - JAVA_OPTS=${JAVA_OPTS:--Xmx2048m -Djava.awt.headless=true}
      - TZ=${TIMEZONE:-UTC}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  jenkins_home:
  jenkins_sqlite:

networks:
  default:
    name: jenkins_network
