# Docker Compose file for CouchDB
# GitHub: https://github.com/vintagedon/docker-compose-cookbook
# Description: This Docker Compose file sets up a CouchDB instance with customizable configuration.

version: '3.8'
services:
  couchdb:
    image: couchdb:latest
    container_name: ${COUCHDB_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
      - NODENAME=${COUCHDB_NODENAME}
    ports:
      - "${COUCHDB_PORT}:5984"
    volumes:
      - ${COUCHDB_DATA_DIR}:/opt/couchdb/data
      - ${COUCHDB_CONFIG_DIR}:/opt/couchdb/etc/local.d
    command: >
      /opt/couchdb/bin/couchdb
      -couch_ini /opt/couchdb/etc/default.ini /opt/couchdb/etc/local.ini /opt/couchdb/etc/local.d/docker.ini
      -chkconfig
      -c couchdb.max_dbs_open=${COUCHDB_MAX_DBS_OPEN:-500}
      -c chttpd.max_connections=${COUCHDB_MAX_CONNECTIONS:-2048}
      -c couch_httpd_auth.timeout=${COUCHDB_SESSION_TIMEOUT:-600}
      -c couchdb.os_process_timeout=${COUCHDB_OS_PROCESS_TIMEOUT:-5000}
      -c couch_httpd_auth.allow_persistent_cookies=${COUCHDB_ALLOW_PERSISTENT_COOKIES:-true}
      -c couchdb.max_document_size=${COUCHDB_MAX_DOCUMENT_SIZE:-4294967296}

networks:
  default:
    name: couchdb_network
