# Docker Compose file for Graylog
# GitHub: https://github.com/vintagedon/docker-compose-cookbook/monitoring-logging/graylog
# Description: This Docker Compose file sets up a Graylog instance with customizable configuration.

version: "3.8"
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    restart: unless-stopped

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.2
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}
      - GRAYLOG_ELASTICSEARCH_HOSTS=${GRAYLOG_ELASTICSEARCH_HOSTS}
      - GRAYLOG_MONGODB_URI=${GRAYLOG_MONGODB_URI}
      - GRAYLOG_SMTP_SERVER=${GRAYLOG_SMTP_SERVER:-}
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: unless-stopped
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - ${GRAYLOG_HTTP_PORT:-9000}:9000
      # Syslog TCP
      - ${GRAYLOG_SYSLOG_TCP_PORT:-1514}:1514
      # Syslog UDP
      - ${GRAYLOG_SYSLOG_UDP_PORT:-1514}:1514/udp
      # GELF TCP
      - ${GRAYLOG_GELF_TCP_PORT:-12201}:12201
      # GELF UDP
      - ${GRAYLOG_GELF_UDP_PORT:-12201}:12201/udp

volumes:
  mongodb_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
  graylog_journal:
    driver: local

networks:
  default:
    name: graylog_network
