# Name: nginx-proxy-manager-sqlite/.docker/docker-compose.yaml
#
# Description:
# Docker compose file for Ngnix Proxy Manager w/sqlite
# https://nginxproxymanager.com/
#
# Project: https://github.com/vintagedon/infrastructure-scripting/blob/main/docker-compose/
# License: Apache-2.0

version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '${PUBLIC_HTTP_PORT}:80'
      - '${PUBLIC_HTTPS_PORT}:443'
      - '${NPM_ADMIN_PORT}:81'
    volumes:
      - ${DATA_DIR}/data:/data
      - ${LETSENCRYPT_DIR}/letsencrypt:/etc/letsencrypt
